name: Tests mandataire électron
on:
  push:
    branches:
      - principale
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - principale
    paths-ignore:
        - '**.md'

defaults:
  run:
    shell: 'bash'

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  formatter:
    name: Formatter
    runs-on: ubuntu-24.04
    steps:
      
      - name: Ouvrir la branche
        uses: actions/checkout@v4

      - name: Installer pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Préparation de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
          cache: 'pnpm'

      - name: Installer
        run: pnpm install

      - name: Formatter
        run: pnpm formatter

      - name: Envoyer couverure à Codecov
        uses: codecov/codecov-action@v5

  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      
      - name: Ouvrir la branche
        uses: actions/checkout@v4

      - name: Installer pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Préparation de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
          cache: 'pnpm'

      - name: Installer
        run: pnpm install
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

      # De https://github.com/microsoft/playwright/issues/34251
      - run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
        if: contains(matrix.os, 'ubuntu')

      - name: Vérifier les tests (Ubuntu)
        run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- pnpm test
        if: contains(matrix.os, 'ubuntu')

      - name: Vérifier les tests
        run: pnpm test
        if: "!contains(matrix.os, 'ubuntu')"

      - name: Envoyer couverure à Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
