name: Tests mandataire électron
on:
  push:
    branches:
      - principale
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - principale
    paths-ignore:
        - '**.md'

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      
      - name: Ouvrir la branche
        uses: actions/checkout@v4

      - name: Installer pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Préparation de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'pnpm'

      - name: Installer
        run: pnpm install

      - name: Installer playwright
        run: npx playwright install

      - name: Vérifier les tests (Ubuntu)
        run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- pnpm test
        if: matrix.os == 'ubuntu-latest'

      - name: Vérifier les tests
        run: pnpm test
        if: matrix.os != 'ubuntu-latest'

      - name: Envoyer couverure à Codecov
        uses: codecov/codecov-action@v4
